In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv("Bengaluru_House_Data.csv")

In [3]:
df.head()

,area_type,availability,location,size,society,total_sqft,bath,balcony,price
0,Super built-up Area,19-Dec,Electronic City Phase II,2 BHK,Coomee,1056,2.0,1.0,39.07
1,Plot Area,Ready To Move,Chikka Tirupathi,4 Bedroom,Theanmp,2600,5.0,3.0,120.00
2,Built-up Area,Ready To Move,Uttarahalli,3 BHK,NaN,1440,2.0,3.0,62.00
3,Super built-up Area,Ready To Move,Lingadheeranahalli,3 BHK,Soiewre,1521,3.0,1.0,95.00
4,Super built-up Area,Ready To Move,Kothanur,2 BHK,NaN,1200,2.0,1.0,51.00

In [4]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

In [5]:
df2=df.drop(['area_type','availability','society','balcony'],axis=1)

In [6]:
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [7]:
df2.isnull().sum()

location       1
size          16
total_sqft     0
bath          73
price          0
dtype: int64

In [8]:
df2.dropna(inplace=True)

In [9]:
df2.head()

                   location       size total_sqft  bath   price
0  Electronic City Phase II      2 BHK       1056   2.0   39.07
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00
2               Uttarahalli      3 BHK       1440   2.0   62.00
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00
4                  Kothanur      2 BHK       1200   2.0   51.00

In [10]:
df2['bhk']=df2['size'].apply(lambda x: int(x.split()[0]))

In [11]:
df2.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07    2
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00    4
2               Uttarahalli      3 BHK       1440   2.0   62.00    3
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00    3
4                  Kothanur      2 BHK       1200   2.0   51.00    2

In [12]:
df2.drop('size',axis=1)

                       location total_sqft  bath   price  bhk
0      Electronic City Phase II       1056   2.0   39.07    2
1              Chikka Tirupathi       2600   5.0  120.00    4
2                   Uttarahalli       1440   2.0   62.00    3
3            Lingadheeranahalli       1521   3.0   95.00    3
4                      Kothanur       1200   2.0   51.00    2
...                         ...        ...   ...     ...  ...
13315                Whitefield       3453   4.0  231.00    5
13316             Richards Town       3600   5.0  400.00    4
13317     Raja Rajeshwari Nagar       1141   2.0   60.00    2
13318           Padmanabhanagar       4689   4.0  488.00    4
13319              Doddathoguru        550   1.0   17.00    1

[13246 rows x 5 columns]

In [13]:
df2['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

# divide this data into convertable or non convertable data

In [14]:
def is_float(x):
    try:
        float(x)
    except:
        return False 
    return True

In [15]:
df2[~df2['total_sqft'].apply(is_float)].head(10)   # theese data is non convertable in float

               location       size      total_sqft  bath    price  bhk
30            Yelahanka      4 BHK     2100 - 2850   4.0  186.000    4
122              Hebbal      4 BHK     3067 - 8156   4.0  477.000    4
137  8th Phase JP Nagar      2 BHK     1042 - 1105   2.0   54.005    2
165            Sarjapur      2 BHK     1145 - 1340   2.0   43.490    2
188            KR Puram      2 BHK     1015 - 1540   2.0   56.800    2
410             Kengeri      1 BHK  34.46Sq. Meter   1.0   18.500    1
549         Hennur Road      2 BHK     1195 - 1440   2.0   63.770    2
648             Arekere  9 Bedroom       4125Perch   9.0  265.000    9
661           Yelahanka      2 BHK     1120 - 1145   2.0   48.130    2
672        Bettahalsoor  4 Bedroom     3090 - 5002   4.0  445.000    4

# now make this data useable by having average from this data

In [16]:
s1='3455-4545'
x=s1.split('-')
(int(x[0])+int(x[1]))/2

4000.0

In [17]:
def convert_sqft_to_num(x):
    tokens=x.split('-')
    if len(tokens)==2:
        return(float(x[0])+float(x[1]))/2
    try:
        return(float)
    except:
        return None

In [18]:
df3=df2.copy()

In [19]:
df3.location=df3['location'].apply(lambda x : x.strip())
location_stats=df3.location.value_counts(ascending=False)
location_stats

location
Whitefield                           535
Sarjapur  Road                       392
Electronic City                      304
Kanakpura Road                       266
Thanisandra                          236
                                    ...
Duddanahalli                           1
Beml layout, Rajarajeshwari nagar      1
Sabari Nagar                           1
Ashraya Layout                         1
Whitefield ECC Road                    1
Name: count, Length: 1293, dtype: int64

In [20]:
# find the length of a places which are repeating less than 10

In [21]:
len(location_stats[location_stats>10])

241

In [22]:
len(location_stats)

1293

In [23]:
len(location_stats[location_stats<=10])

1052

# any location which is under 10 should be grouped as other loction to make this short to remember 
# cause label encoder will make ueless data by applying 0 at many spaces

In [24]:
location_stats_less10=location_stats[location_stats<=10]
location_stats_less10

location
Nagadevanahalli                      10
Ganga Nagar                          10
Kalkere                              10
BTM 1st Stage                        10
Sector 1 HSR Layout                  10
                                     ..
Duddanahalli                          1
Beml layout, Rajarajeshwari nagar     1
Sabari Nagar                          1
Ashraya Layout                        1
Whitefield ECC Road                   1
Name: count, Length: 1052, dtype: int64

In [25]:
df3.location=df3.location.apply(lambda x: 'unknown' if x in location_stats_less10 else x)
len(df3.location.unique())                      # less than wale unknown naam se save ho  gaye isse sare

242

In [26]:
df3['bhk'].unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18])

# upto 11 bhk is fine but more than 11 bhk will not be treated as importtant data its useless

In [27]:
df3.bhk=df3.bhk.apply(lambda x: x if x<=11 else np.nan)
df3.bhk.unique()

array([ 2.,  4.,  3.,  6.,  1.,  8.,  7.,  5., 11.,  9., nan, 10.])

In [28]:
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
bhk           8
dtype: int64

In [29]:
df3.bhk=df3.bhk.fillna(df3.bhk.mode()[0])

In [30]:
df3.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
bhk           0
dtype: int64

# as a data scientist , when u have a conversation with your business mamager ( who has expertise in real state), he will tell you that the
# that the normal area for 1sqft shoulbe be upto or more than 300 , soo overall is 1bhk must have 300 or more sqft , if any bhk has lower than the ideal sqft soo unhe  aise treat krenge

In [31]:
df3.head()

                   location       size total_sqft  bath   price  bhk
0  Electronic City Phase II      2 BHK       1056   2.0   39.07  2.0
1          Chikka Tirupathi  4 Bedroom       2600   5.0  120.00  4.0
2               Uttarahalli      3 BHK       1440   2.0   62.00  3.0
3        Lingadheeranahalli      3 BHK       1521   3.0   95.00  3.0
4                  Kothanur      2 BHK       1200   2.0   51.00  2.0

In [32]:
df3[df3.total_sqft/df3.bhk<300].head()

TypeError: unsupported operand type(s) for /: 'str' and 'float'

In [33]:
df3[df3['total_sqft']/df3['bhk']<300]

TypeError: unsupported operand type(s) for /: 'str' and 'float'